# Generated by Django 5.0.2 on 2025-07-28 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utility', '0017_business_type_call_status_requirent_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('office', 'Office Space'), ('shop', 'Shop/Showroom'), ('warehouse', 'Warehouse'), ('industrial', 'Industrial Land'), ('commercial_land', 'Commercial Land')], max_length=50)),
                ('sale_type', models.CharField(choices=[('sale', 'Sale'), ('resale', 'Resale'), ('rental', 'Rental')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('builtup_area', models.FloatField(blank=True, help_text='Area in sq. ft.', null=True)),
                ('floor_no', models.IntegerField(blank=True, null=True)),
                ('total_floors', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('furnishing', models.CharField(choices=[('unfurnished', 'Unfurnished'), ('semi', 'Semi-Furnished'), ('fully', 'Fully-Furnished')], default='unfurnished', max_length=50)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.city')),
                ('locality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.locality')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommercialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='commercial_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.commercialproperty')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentialProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('flat', 'Flat/Apartment'), ('house', 'Independent House'), ('villa', 'Villa'), ('plot', 'Residential Plot')], max_length=50)),
                ('sale_type', models.CharField(choices=[('sale', 'Sale'), ('resale', 'Resale'), ('rental', 'Rental')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('builtup_area', models.FloatField(blank=True, help_text='Area in sq. ft.', null=True)),
                ('carpet_area', models.FloatField(blank=True, help_text='Carpet Area in sq. ft.', null=True)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('balconies', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('furnishing', models.CharField(choices=[('unfurnished', 'Unfurnished'), ('semi', 'Semi-Furnished'), ('fully', 'Fully-Furnished')], default='unfurnished', max_length=50)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.city')),
                ('locality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.locality')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResidentialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='residential_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.residentialproperty')),
            ],
        ),
    ]
